/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ArticlesApi,
  BillboardsApi,
  CommentsApi,
  FollowedTagsApi,
  FollowersApi,
  OrganizationsApi,
  PagesApi,
  PodcastEpisodesApi,
  ProfileImagesApi,
  ReactionsApi,
  ReadinglistApi,
  SegmentsApi,
  TagsApi,
  UsersApi,
  VideosApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { DevCustom } from "./client-custom";

export class Dev extends DevCustom {
  readonly articles: ArticlesApi;
  readonly billboards: BillboardsApi;
  readonly comments: CommentsApi;
  readonly followedTags: FollowedTagsApi;
  readonly followers: FollowersApi;
  readonly organizations: OrganizationsApi;
  readonly pages: PagesApi;
  readonly podcastEpisodes: PodcastEpisodesApi;
  readonly profileImages: ProfileImagesApi;
  readonly reactions: ReactionsApi;
  readonly readinglist: ReadinglistApi;
  readonly segments: SegmentsApi;
  readonly tags: TagsApi;
  readonly users: UsersApi;
  readonly videos: VideosApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.articles = new ArticlesApi(configuration);
    this.billboards = new BillboardsApi(configuration);
    this.comments = new CommentsApi(configuration);
    this.followedTags = new FollowedTagsApi(configuration);
    this.followers = new FollowersApi(configuration);
    this.organizations = new OrganizationsApi(configuration);
    this.pages = new PagesApi(configuration);
    this.podcastEpisodes = new PodcastEpisodesApi(configuration);
    this.profileImages = new ProfileImagesApi(configuration);
    this.reactions = new ReactionsApi(configuration);
    this.readinglist = new ReadinglistApi(configuration);
    this.segments = new SegmentsApi(configuration);
    this.tags = new TagsApi(configuration);
    this.users = new UsersApi(configuration);
    this.videos = new VideosApi(configuration);
  }

}
