/* tslint:disable */
/* eslint-disable */
/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { FollowersGetList401Response } from '../models';
// @ts-ignore
import { FollowersGetListResponseInner } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * FollowersApi - axios parameter creator
 * @export
 */
export const FollowersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This endpoint allows the client to retrieve a list of the followers they have.         \"Followers\" are users that are following other users on the website.         It supports pagination, each page will contain 80 followers by default.
         * @summary Followers
         * @param {number} [page] Pagination page
         * @param {number} [perPage] Page size (the number of items to return per page). The default maximum value can be overridden by \&quot;API_PER_PAGE_MAX\&quot; environment variable.
         * @param {string} [sort] Default is \&#39;created_at\&#39;. Specifies the sort order for the created_at param of the follow                                 relationship. To sort by newest followers first (descending order) specify                                 ?sort&#x3D;-created_at.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList: async (page?: number, perPage?: number, sort?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/followers/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api-key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "api-key", keyParamName: "apiKey", configuration })
            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/followers/users',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FollowersApi - functional programming interface
 * @export
 */
export const FollowersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FollowersApiAxiosParamCreator(configuration)
    return {
        /**
         * This endpoint allows the client to retrieve a list of the followers they have.         \"Followers\" are users that are following other users on the website.         It supports pagination, each page will contain 80 followers by default.
         * @summary Followers
         * @param {FollowersApiGetListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getList(requestParameters: FollowersApiGetListRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FollowersGetListResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getList(requestParameters.page, requestParameters.perPage, requestParameters.sort, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FollowersApi - factory interface
 * @export
 */
export const FollowersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FollowersApiFp(configuration)
    return {
        /**
         * This endpoint allows the client to retrieve a list of the followers they have.         \"Followers\" are users that are following other users on the website.         It supports pagination, each page will contain 80 followers by default.
         * @summary Followers
         * @param {FollowersApiGetListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList(requestParameters: FollowersApiGetListRequest = {}, options?: AxiosRequestConfig): AxiosPromise<Array<FollowersGetListResponseInner>> {
            return localVarFp.getList(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getList operation in FollowersApi.
 * @export
 * @interface FollowersApiGetListRequest
 */
export type FollowersApiGetListRequest = {
    
    /**
    * Pagination page
    * @type {number}
    * @memberof FollowersApiGetList
    */
    readonly page?: number
    
    /**
    * Page size (the number of items to return per page). The default maximum value can be overridden by \"API_PER_PAGE_MAX\" environment variable.
    * @type {number}
    * @memberof FollowersApiGetList
    */
    readonly perPage?: number
    
    /**
    * Default is \'created_at\'. Specifies the sort order for the created_at param of the follow                                 relationship. To sort by newest followers first (descending order) specify                                 ?sort=-created_at.
    * @type {string}
    * @memberof FollowersApiGetList
    */
    readonly sort?: string
    
}

/**
 * FollowersApiGenerated - object-oriented interface
 * @export
 * @class FollowersApiGenerated
 * @extends {BaseAPI}
 */
export class FollowersApiGenerated extends BaseAPI {
    /**
     * This endpoint allows the client to retrieve a list of the followers they have.         \"Followers\" are users that are following other users on the website.         It supports pagination, each page will contain 80 followers by default.
     * @summary Followers
     * @param {FollowersApiGetListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FollowersApiGenerated
     */
    public getList(requestParameters: FollowersApiGetListRequest = {}, options?: AxiosRequestConfig) {
        return FollowersApiFp(this.configuration).getList(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
