/* tslint:disable */
/* eslint-disable */
/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { FollowedTag } from '../models';
// @ts-ignore
import { FollowedtagsGetTagList401Response } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * FollowedTagsApi - axios parameter creator
 * @export
 */
export const FollowedTagsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This endpoint allows the client to retrieve a list of the tags they follow.
         * @summary Followed Tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTagList: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/follows/tags`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api-key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "api-key", keyParamName: "apiKey", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/follows/tags',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FollowedTagsApi - functional programming interface
 * @export
 */
export const FollowedTagsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FollowedTagsApiAxiosParamCreator(configuration)
    return {
        /**
         * This endpoint allows the client to retrieve a list of the tags they follow.
         * @summary Followed Tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTagList(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FollowedTag>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTagList(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FollowedTagsApi - factory interface
 * @export
 */
export const FollowedTagsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FollowedTagsApiFp(configuration)
    return {
        /**
         * This endpoint allows the client to retrieve a list of the tags they follow.
         * @summary Followed Tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTagList(options?: AxiosRequestConfig): AxiosPromise<Array<FollowedTag>> {
            return localVarFp.getTagList(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FollowedTagsApiGenerated - object-oriented interface
 * @export
 * @class FollowedTagsApiGenerated
 * @extends {BaseAPI}
 */
export class FollowedTagsApiGenerated extends BaseAPI {
    /**
     * This endpoint allows the client to retrieve a list of the tags they follow.
     * @summary Followed Tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FollowedTagsApiGenerated
     */
    public getTagList(options?: AxiosRequestConfig) {
        return FollowedTagsApiFp(this.configuration).getTagList(options).then((request) => request(this.axios, this.basePath));
    }
}
