/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ArticlesUpdateByIdResponseUser } from './articles-update-by-id-response-user';

/**
 * 
 * @export
 * @interface ArticlesUpdateByIdResponse
 */
export interface ArticlesUpdateByIdResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ArticlesUpdateByIdResponse
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'type_of'?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticlesUpdateByIdResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'readable_publish_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'path'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'url'?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticlesUpdateByIdResponse
     */
    'comments_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticlesUpdateByIdResponse
     */
    'public_reactions_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'collection_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'published_timestamp'?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticlesUpdateByIdResponse
     */
    'positive_reactions_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'cover_image'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'social_image'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'canonical_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'edited_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'crossposted_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'published_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'last_comment_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticlesUpdateByIdResponse
     */
    'reading_time_minutes'?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'tag_list'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'body_html'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlesUpdateByIdResponse
     */
    'body_markdown'?: string;
    /**
     * 
     * @type {ArticlesUpdateByIdResponseUser}
     * @memberof ArticlesUpdateByIdResponse
     */
    'user'?: ArticlesUpdateByIdResponseUser;
}

