/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ArticleArticle
 */
export interface ArticleArticle {
    /**
     * 
     * @type {string}
     * @memberof ArticleArticle
     */
    'tags'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleArticle
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleArticle
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleArticle
     */
    'body_markdown'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleArticle
     */
    'published'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ArticleArticle
     */
    'series'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticleArticle
     */
    'main_image'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticleArticle
     */
    'canonical_url'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ArticleArticle
     */
    'organization_id'?: number | null;
}

