/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ArticleFlareTag } from './article-flare-tag';
import { SharedOrganization } from './shared-organization';
import { SharedUser } from './shared-user';

/**
 * Representation of an article or post returned in a list
 * @export
 * @interface ArticleIndex
 */
export interface ArticleIndex {
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'tags': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'type_of': string;
    /**
     * 
     * @type {number}
     * @memberof ArticleIndex
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'cover_image': string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'readable_publish_date': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'social_image': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArticleIndex
     */
    'tag_list': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'path': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'canonical_url': string;
    /**
     * 
     * @type {number}
     * @memberof ArticleIndex
     */
    'positive_reactions_count': number;
    /**
     * 
     * @type {number}
     * @memberof ArticleIndex
     */
    'public_reactions_count': number;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'edited_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'crossposted_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'published_at': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIndex
     */
    'last_comment_at': string;
    /**
     * Crossposting or published date time
     * @type {string}
     * @memberof ArticleIndex
     */
    'published_timestamp': string;
    /**
     * Reading time, in minutes
     * @type {number}
     * @memberof ArticleIndex
     */
    'reading_time_minutes': number;
    /**
     * 
     * @type {SharedUser}
     * @memberof ArticleIndex
     */
    'user': SharedUser;
    /**
     * 
     * @type {ArticleFlareTag}
     * @memberof ArticleIndex
     */
    'flare_tag'?: ArticleFlareTag;
    /**
     * 
     * @type {SharedOrganization}
     * @memberof ArticleIndex
     */
    'organization'?: SharedOrganization;
}

