/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Billboard, aka Widget, ex. Display Ad
 * @export
 * @interface Billboard
 */
export interface Billboard {
    /**
     * The ID of the Billboard
     * @type {number}
     * @memberof Billboard
     */
    'id'?: number;
    /**
     * For internal use, helps distinguish ads from one another
     * @type {string}
     * @memberof Billboard
     */
    'name': string;
    /**
     * The text (in markdown) of the ad (required)
     * @type {string}
     * @memberof Billboard
     */
    'body_markdown': string;
    /**
     * Ad must be both published and approved to be in rotation
     * @type {boolean}
     * @memberof Billboard
     */
    'approved'?: boolean;
    /**
     * Ad must be both published and approved to be in rotation
     * @type {boolean}
     * @memberof Billboard
     */
    'published'?: boolean;
    /**
     * Identifies the organization to which the ad belongs
     * @type {number}
     * @memberof Billboard
     */
    'organization_id'?: number | null;
    /**
     * Identifies the user who created the ad.
     * @type {number}
     * @memberof Billboard
     */
    'creator_id'?: number | null;
    /**
     * Identifies which area of site layout the ad can appear in
     * @type {string}
     * @memberof Billboard
     */
    'placement_area': BillboardPlacementAreaEnum;
    /**
     * Tags on which this ad can be displayed (blank is all/any tags)
     * @type {string}
     * @memberof Billboard
     */
    'tag_list'?: string;
    /**
     * Articles this ad should *not* appear on (blank means no articles are disallowed, and this ad can appear next to any/all articles). Comma-separated list of integer Article IDs
     * @type {string}
     * @memberof Billboard
     */
    'exclude_article_ids'?: string | null;
    /**
     * Specifies a specific audience segment who will see this billboard
     * @type {number}
     * @memberof Billboard
     */
    'audience_segment_id'?: number;
    /**
     * Specifies a group of users who will see this billboard (must match audience_segment_id if both provided)
     * @type {string}
     * @memberof Billboard
     */
    'audience_segment_type'?: BillboardAudienceSegmentTypeEnum;
    /**
     * Locations to show this billboard in (blank means it will be shown in all locations). Specified as a comma-separated list or array of ISO 3166-2 country and optionally region codes)
     * @type {Array<string>}
     * @memberof Billboard
     */
    'target_geolocations'?: Array<string>;
    /**
     * Potentially limits visitors to whom the ad is visible
     * @type {string}
     * @memberof Billboard
     */
    'display_to'?: BillboardDisplayToEnum;
    /**
     * Types of the billboards: in_house (created by admins), community (created by an entity, appears on entity\'s content), external ( created by an entity, or a non-entity, can appear everywhere) 
     * @type {string}
     * @memberof Billboard
     */
    'type_of'?: BillboardTypeOfEnum;
}

type BillboardPlacementAreaEnum = 'sidebar_left' | 'sidebar_left_2' | 'sidebar_right' | 'feed_first' | 'feed_second' | 'feed_third' | 'home_hero' | 'post_sidebar' | 'post_comments'
type BillboardAudienceSegmentTypeEnum = 'manual' | 'trusted' | 'posted' | 'no_posts_yet' | 'dark_theme' | 'light_theme' | 'no_experience' | 'experience1' | 'experience2' | 'experience3' | 'experience4' | 'experience5'
type BillboardDisplayToEnum = 'all' | 'logged_in' | 'logged_out'
type BillboardTypeOfEnum = 'in_house' | 'community' | 'external'


