/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommentsGetThreadedCommentResponseUser } from './comments-get-threaded-comment-response-user';

/**
 * 
 * @export
 * @interface CommentsGetThreadedCommentResponse
 */
export interface CommentsGetThreadedCommentResponse {
    /**
     * 
     * @type {string}
     * @memberof CommentsGetThreadedCommentResponse
     */
    'type_of'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentsGetThreadedCommentResponse
     */
    'id_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentsGetThreadedCommentResponse
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentsGetThreadedCommentResponse
     */
    'body_html'?: string;
    /**
     * 
     * @type {CommentsGetThreadedCommentResponseUser}
     * @memberof CommentsGetThreadedCommentResponse
     */
    'user'?: CommentsGetThreadedCommentResponseUser;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommentsGetThreadedCommentResponse
     */
    'children'?: Array<string>;
}

