/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The representation of a user
 * @export
 * @interface ExtendedUser
 */
export interface ExtendedUser {
    /**
     * 
     * @type {string}
     * @memberof ExtendedUser
     */
    'summary'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExtendedUser
     */
    'type_of'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtendedUser
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtendedUser
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedUser
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedUser
     */
    'twitter_username'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedUser
     */
    'github_username'?: string;
    /**
     * Email (if user allows displaying email on their profile) or nil
     * @type {string}
     * @memberof ExtendedUser
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExtendedUser
     */
    'website_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExtendedUser
     */
    'location'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExtendedUser
     */
    'joined_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedUser
     */
    'profile_image'?: string;
    /**
     * ids of the badges awarded to the user
     * @type {Array<number>}
     * @memberof ExtendedUser
     */
    'badge_ids'?: Array<number>;
}

