/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A follower
 * @export
 * @interface FollowersGetListResponseInner
 */
export interface FollowersGetListResponseInner {
    /**
     * user_follower by default
     * @type {string}
     * @memberof FollowersGetListResponseInner
     */
    'type_of'?: string;
    /**
     * 
     * @type {number}
     * @memberof FollowersGetListResponseInner
     */
    'id'?: number;
    /**
     * The follower\'s user id
     * @type {number}
     * @memberof FollowersGetListResponseInner
     */
    'user_id'?: number;
    /**
     * The follower\'s name
     * @type {string}
     * @memberof FollowersGetListResponseInner
     */
    'name'?: string;
    /**
     * A path to the follower\'s profile
     * @type {string}
     * @memberof FollowersGetListResponseInner
     */
    'path'?: string;
    /**
     * Profile image (640x640)
     * @type {string}
     * @memberof FollowersGetListResponseInner
     */
    'profile_image'?: string;
}

