/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Representation of an Organization
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'summary'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'type_of'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'twitter_username'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'github_username'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'joined_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'tech_stack'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'tag_line'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'story'?: string | null;
}

