/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PagesCreateNewPageResponseSocialImage } from './pages-create-new-page-response-social-image';

/**
 * 
 * @export
 * @interface PagesCreateNewPageResponse
 */
export interface PagesCreateNewPageResponse {
    /**
     * 
     * @type {string}
     * @memberof PagesCreateNewPageResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagesCreateNewPageResponse
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof PagesCreateNewPageResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PagesCreateNewPageResponse
     */
    'slug'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PagesCreateNewPageResponse
     */
    'is_top_level_path'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagesCreateNewPageResponse
     */
    'landing_page'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PagesCreateNewPageResponse
     */
    'body_html'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PagesCreateNewPageResponse
     */
    'body_json'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PagesCreateNewPageResponse
     */
    'body_markdown'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagesCreateNewPageResponse
     */
    'processed_html'?: string;
    /**
     * 
     * @type {PagesCreateNewPageResponseSocialImage}
     * @memberof PagesCreateNewPageResponse
     */
    'social_image'?: PagesCreateNewPageResponseSocialImage;
    /**
     * 
     * @type {string}
     * @memberof PagesCreateNewPageResponse
     */
    'template'?: string;
}

