/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PagesRemovePageById422ResponseDoubledModule } from './pages-remove-page-by-id422-response-doubled-module';

/**
 * 
 * @export
 * @interface PagesRemovePageById422Response
 */
export interface PagesRemovePageById422Response {
    /**
     * 
     * @type {PagesRemovePageById422ResponseDoubledModule}
     * @memberof PagesRemovePageById422Response
     */
    'doubled_module'?: PagesRemovePageById422ResponseDoubledModule;
    /**
     * 
     * @type {boolean}
     * @memberof PagesRemovePageById422Response
     */
    '__expired'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PagesRemovePageById422Response
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PagesRemovePageById422Response
     */
    '__sending_message'?: string | null;
}

