/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PagesCreateNewPageRequest
 */
export interface PagesCreateNewPageRequest {
    /**
     * Title of the page
     * @type {string}
     * @memberof PagesCreateNewPageRequest
     */
    'title'?: string;
    /**
     * For internal use, helps similar pages from one another
     * @type {string}
     * @memberof PagesCreateNewPageRequest
     */
    'description'?: string;
    /**
     * Used to link to this page in URLs, must be unique and URL-safe
     * @type {string}
     * @memberof PagesCreateNewPageRequest
     */
    'slug'?: string;
    /**
     * The text (in markdown) of the ad (required)
     * @type {string}
     * @memberof PagesCreateNewPageRequest
     */
    'body_markdown'?: string;
    /**
     * For JSON pages, the JSON body
     * @type {string}
     * @memberof PagesCreateNewPageRequest
     */
    'body_json'?: string;
    /**
     * If true, the page is available at \'/{slug}\' instead of \'/page/{slug}\', use with caution
     * @type {boolean}
     * @memberof PagesCreateNewPageRequest
     */
    'is_top_level_path'?: boolean;
    /**
     * Controls what kind of layout the page is rendered in
     * @type {string}
     * @memberof PagesCreateNewPageRequest
     */
    'template'?: PagesCreateNewPageRequestTemplateEnum;
}

type PagesCreateNewPageRequestTemplateEnum = 'contained' | 'full_within_layout' | 'nav_bar_included' | 'json'


