/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A profile image object
 * @export
 * @interface ProfileImage
 */
export interface ProfileImage {
    /**
     * Return profile_image
     * @type {string}
     * @memberof ProfileImage
     */
    'type_of'?: string;
    /**
     * Determines the type of the profile image owner (user or organization)
     * @type {string}
     * @memberof ProfileImage
     */
    'image_of'?: string;
    /**
     * Profile image (640x640)
     * @type {string}
     * @memberof ProfileImage
     */
    'profile_image'?: string;
    /**
     * Profile image (90x90)
     * @type {string}
     * @memberof ProfileImage
     */
    'profile_image_90'?: string;
}

