/*
Forem API V1

Access Forem articles, users and other resources via API.
        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
        All endpoints can be accessed with the 'api-key' header and a accept header, but
        some of them are accessible publicly without authentication.

        Dates and date times, unless otherwise specified, must be in
        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VideoArticleUser } from './video-article-user';

/**
 * Representation of an Article with video
 * @export
 * @interface VideoArticle
 */
export interface VideoArticle {
    /**
     * 
     * @type {string}
     * @memberof VideoArticle
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoArticle
     */
    'type_of'?: string;
    /**
     * 
     * @type {number}
     * @memberof VideoArticle
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof VideoArticle
     */
    'path'?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoArticle
     */
    'cloudinary_video_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof VideoArticle
     */
    'user_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof VideoArticle
     */
    'video_duration_in_minutes'?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoArticle
     */
    'video_source_url'?: string;
    /**
     * 
     * @type {VideoArticleUser}
     * @memberof VideoArticle
     */
    'user'?: VideoArticleUser;
}

